sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t zaldanaraul/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zaldanaraul/docker-react npm run test